steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dealbrief/scanner-api:latest', 
           '-f', 'Dockerfile.api', '.']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/dealbrief/scanner-api:latest'