steps:
  # Build worker only
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-worker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/precise-victory-467219-s4/dealbrief/scanner-worker:latest',
      '-f', 'Dockerfile.worker',
      '.'
    ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-worker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/precise-victory-467219-s4/dealbrief/scanner-worker:latest'
    ]
    waitFor: ['build-worker']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-worker-job'
    entrypoint: 'gcloud'
    args: [
      'run', 'jobs', 'update', 'scanner-job',
      '--image', 'us-central1-docker.pkg.dev/precise-victory-467219-s4/dealbrief/scanner-worker:latest',
      '--region', 'us-central1'
    ]
    waitFor: ['push-worker']

timeout: 900s
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY