services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      cache_from:
        - type=registry,ref=${REGISTRY_BASE}/${PROJECT_ID}/dealbrief/scanner-worker:cache
    image: scanner-worker:local
    env_file:
      - .env.docker

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      cache_from:
        - type=registry,ref=${REGISTRY_BASE}/${PROJECT_ID}/dealbrief/scanner-api:cache
    image: scanner-api:local
    env_file:
      - .env.docker

  reports:
    build:
      context: .
      dockerfile: Dockerfile.reports
      cache_from:
        - type=registry,ref=${REGISTRY_BASE}/${PROJECT_ID}/dealbrief/scanner-reports:cache
    image: scanner-reports:local
    env_file:
      - .env.docker